project:
  type: website

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - theory.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true










quartodoc:
  # the name used to import the package you want to create reference docs for
  package: bindcurve

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - load_csv
        - preview



