project:
  type: website

website:
  title: "BindCurve"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - theory.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
      - section: "Basics"
        href: basics-summary.qmd
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: advanced.qmd
        contents:
          - raw-code.qmd
          - custom-theme.qmd
      - acknowlegment.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true










quartodoc:
  # the name used to import the package you want to create reference docs for
  package: bindcurve

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - load_csv
        - preview



