---
title: "Welcome to BindCurve"
---

This website contains documentation for `bindcurve` - a lightweight Python package that allows fitting and plotting of binding curves. It contains logistic model for fitting IC50 or logIC50, and also  exact polynomial models for fitting Kd from both direct and competitive binding experiments. Fixing lower and upper asymptotes of the models during fitting is supported, as well as fixing the slope in logistic models. Additionally, IC50 values can be converted to Kd using conversion models.

`bindcurve` is intended as a simple tool for Python-based workflows in Jupyter notebooks or similar tools. Even if you have never used Python before, you can fit your binding curve in less than 5 lines of code. The results can be conveniently plotted with another few lines of code or simply reported in formatted output.


::: {.callout-warning}
`bindcurve` is currently in Alpha version. Changes to API might happen momentarily without notice. If you encounter bugs, please report them on GitHub. 
:::

