name: Lint with Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: python -m pip install ruff

      - name: Run Ruff
        run: ruff check bindcurve/conversion bindcurve/datasets bindcurve/modeling bindcurve/fitting bindcurve/results bindcurve/plotting tests
